laravel/routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

Route::get('/why', function () {
	return view('users.why');
})->name('why');

Route::get('/chart', function () {
	return view('users.chart');
})->name('chart');

Route::get('/about', 'HomeController@about')->name('about');
Route::get('/insights', 'HomeController@insight')->name('insight');
Route::get('/contact', 'HomeController@contact')->name('contact');
// Route::post('/enquiry', 'HomeController@enquiry')->name('enquiry.store');

Route::get('/what-we-offer', 'HomeController@what_we_offer')->name('what-we-offer');

Auth::routes();

Route::get('/admin/login', function() {
	return view('admin.login');
});
Route::resource('enquiry', 'EnquiryController');

Route::get('monthly-performance', 'MonthlyPerformanceController@getAll')->name('monthly-performance');

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function(){	
	Route::get('/', 'UserController@admin')->name('home');
	Route::resource('enquiry', 'EnquiryController');
	Route::resource('monthly-performance', 'MonthlyPerformanceController');
	Route::resource('article', 'ArticleController');
	Route::resource('investor-education', 'InvestorEducationController');
	Route::get('clients/{type?}/{name?}', 'UserController@clients')->name('clients');
	Route::delete('client/{id}', 'UserController@destroy')->name('user.destroy');
	Route::get('client/{id}/edit', 'UserController@edit')->name('user.edit');
	Route::post('client', 'UserController@update')->name('user.update');
	Route::get('user-update/{id}/{status}', 'UserController@changeStatus')->name('change-status');
	Route::get('report/{id}', 'UserController@report')->name('report');
	Route::get('import/{id}', 'ImportController@import')->name('import');
	Route::post('upload-excel/', 'ImportController@uploadFile')->name('upload-excel');
	Route::post('import/', 'ImportController@importData')->name('import-data');	
	
});

laravel/resources/views/admin/create_investor_education.blade.php
@extends('admin.layouts.master')
@section('title')
Create Investor Education
@endsection
@php
	$ID = 'investor-education';
@endphp
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3>Create Investor Education</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.investor_education_form')
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/create_monthly_performance.blade.php
@extends('admin.layouts.master')
@section('title')
Create Monthly Performance
@endsection
@php
	$ID = 'monthly-performance';
@endphp
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3> Create Monthly Performance</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.monthly_performance_form')
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/edit_article.blade.php
@extends('admin.layouts.master')
@section('title')
Edit Article
@endsection
@php
	$ID = 'article';
@endphp
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3>Edit Article</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.article_form',['article' => $article])
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/edit_investor_education.blade.php
@extends('admin.layouts.master')
@section('title')
Edit Investor Education
@endsection
@php
	$ID = 'investor-education';
@endphp
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3>Edit Investor Education</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.investor_education_form',['investorEducation' => $investorEducation])
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/edit_monthly_performance.blade.php
@extends('admin.layouts.master')
@section('title')
Edit Monthly Performance
@endsection
@php
	$ID = 'monthly-performance';
@endphp
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3> Edit Monthly Performance</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.'.$ID.'.index') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.monthly_performance_form', ['mp' => $mp])
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/edit_user.blade.php
@extends('admin.layouts.master')
@section('title')
Edit {{ $user->name }} Detail
@endsection
@php
	$ID = 'client';
@endphp
@section('content')
<div class="right_col" role="main">	
	<div class="page-title">
		<div class="title_left">
			<h3> Edit {{ $user->name }} Detail</h3>
		</div>
		<div class="pull-right">
			<a href = "{{ route('admin.clients') }}" class="btn btn-danger">Back</a>
		</div>
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">
					@include('admin.forms.user_form', ['user' => $user])
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/import.blade.php
@extends('admin.layouts.master')
@section('title')
Import Weekly Report of {{ $user->name }}
@endsection

@php
$ID = 'import';
@endphp

@push('header')
<script>
	ID = '{{ $ID }}';
</script>
</style>
@endpush
@section('content')

<div class="right_col" role="main">	
	<div class="page-title">
		<div>
			<h3>
				Upload Excel
				<a href = "{{ route('admin.report',['id' => $user->id]) }}" class="btn btn-primary pull-right"><i class="fa fa-list"></i> Report</a>
			</h3>
		</div>		
	</div>
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_content">					
					<div class="col-md-6">
						<div id = "uploadBox">
							<form action="{{ route('admin.upload-excel') }}" class="form-horizontal form-label-left" method="post"  enctype="multipart/form-data" id = "uploadForm">
								<div class="form-group">
									<label>Select Excel File:</label>
									<input type="file" name = "excel">
									<button type="submit" class="btn btn-primary">Upload</button>
								</div>										
							</form>
						</div>
						<div id = "importBox" class="hidden">
							<form action="{{ route('admin.import-data') }}" class="form-horizontal form-label-left" method="post">
								{{ csrf_field() }}

								<input type="hidden" name="excelFile" id = "excelFile">
								<input type="hidden" name="client" value="{{ $user->id }}">
								<button type="submit" class="btn btn-primary" id = "excelBtn">Import</button>
							</form>
						</div>
					</div>									
					<div class="col-md-6">
						<a href="{{ asset('excels/weekly-report-quants-capital-(sample).xlsx') }}" download class="btn btn-danger">Download Sample xls file</a>
					</div>							
				</div>
			</div>
			<div class="clearfix"></div>
			@if (Session::has('status'))
				<div class="alert alert-success">Successfully Imported, you can Upload any other Excel for {{ $user->name }}</div>
			@endif
		</div>
	</div>
</div>		
</div>
</div>

@endsection

@push('footer')
<script type="text/javascript">
	$('#uploadForm').CRUD({
		url : "{{ route('admin.upload-excel') }}",
		processResponse : function(data){    		
			if(data.msg == 'success'){
				$('#excelFile').val(data.file);
				$('#uploadBox').addClass('hidden');
				$('#importBox').removeClass('hidden');
			}
		}
	});	
	$('#excelBtn').on({
		'click' : function(){			
			$('#loader h1').html('Extracting Data from Excel, Please wait!!');
			$('#loader').removeClass('hidden');
		}
	});
</script>
@endpush

laravel/resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" type="image/x-icon" href="{{ asset('images/fav.png') }}"> 

  <title>{{ config('app.name') }} (Admin)</title>

  <!-- Bootstrap -->
  <link href="{{ asset('admin-assets/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="{{ asset('admin-assets/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
  <!-- NProgress -->
  <link href="{{ asset('admin-assets/nprogress/nprogress.css') }}" rel="stylesheet">
  <!-- Animate.css -->
  <link href="{{ asset('admin-assets/animate.css/animate.min.css') }}" rel="stylesheet">

  <!-- Custom Theme Style -->
  <link href="{{ asset('admin-assets/css/custom.min.css') }}" rel="stylesheet">
</head>

<body class="login">
  <div>
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
      <div class="animate form login_form">
        <section class="login_content">
          <form class="form-horizontal" method="POST" action="{{ route('login') }}">
            {{ csrf_field() }}
            <h1>Admin Login</h1>
            <div>
              <input placeholder="Email" id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autofocus>

              @if ($errors->has('email'))
              <span class="help-block">
                <strong>{{ $errors->first('email') }}</strong>
              </span>
              @endif              
            </div>
            <div>
              <input placeholder="Password" id="password" type="password" class="form-control" name="password" required>

              @if ($errors->has('password'))
              <span class="help-block">
                <strong>{{ $errors->first('password') }}</strong>
              </span>
              @endif              
            </div>
            <div>
              <button class="btn btn-default submit">Log in</button>
              <a class="reset_pass" href="#">Lost your password?</a>
            </div>

            <div class="clearfix"></div>

            <div class="separator">
              {{-- <p class="change_link">New to site?
                <a href="#signup" class="to_register"> Create Account </a>
              </p> --}}

              <div class="clearfix"></div>
              <br />

              {{-- <div class="text-center">
                <img src="{{ asset('images/logo-black.png') }}" width="100%">
              </div> --}}
            </div>
          </form>
        </section>
      </div>
    </div>
  </div>
</body>
</html>

laravel/resources/views/admin/not_allowed.blade.php
@extends('admin.layouts.master')
@section('title')
Sorry {{ Auth::user()->name }}
@endsection
@php
$ID = 'client';
@endphp
@section('content')
<div class="right_col" role="main">		
	<div class="clearfix">
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">				
				<div class="x_content">                
					<h1>Sorry you are not allowed to view these report. <a href="{{ route('admin.report', ['id' => Auth::id()]) }}"><i class="fa fa-home"></i> click here to check yours </a></h1>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

laravel/resources/views/admin/view_articles.blade.php
@extends('admin.layouts.master')

@section('title')
All Articles
@endsection
@push('header')
<!-- Datatables -->
<link href="{{ asset('admin-assets/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
@php
$ID = 'article';
@endphp
@endpush

@section('content')

<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>All Articles</h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">            
            <table id="{{ $ID }}Table" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Sr. No.</th>
                  <th>Image</th>
                  <th>Title</th>                  
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($articles as $k => $a)
                <tr id = "tr-{{ $a->id }}">                  
                  <td>{{ ++$k }}</td>
                  <td><img src="{{ asset($a->ar_image) }}" width="40"></td>
                  <td>{{ $a->ar_title }}</td>
                  <td>
                    <a href = "{{ route('admin.'.$ID.'.edit', ['id' => $a->ar_id]) }}" class="btn btn-success btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                    <form action="{{ route('admin.'.$ID.'.destroy', ['id' => $a->ar_id]) }}" method="post">
                      {{ csrf_field() }}
                      <input type="hidden" name="_method" value="DELETE">
                      <button class="btn btn-danger btn-xs"><i class="fa fa-trash"></i> Delete </button>
                    </form>
                  </td>
                </tr>
                @empty   
                <tr align="center">
                  <td colspan="4">No articles found <a class="btn btn-primary" href="{{ route('admin.'.$ID.'.create') }}">Add one now</a></td>
                </tr>
                @endforelse
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    {{-- <div class="modal fade" id="{{ $ID }}Modal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="{{ $ID }}ModalLabel">Edit {{ $ID }}</h4>
          </div>
          <div class="modal-body">
            @include('admin.forms.category_form')
          </div>
        </div>
      </div>
    </div> --}}

    {{-- <div class="modal fade" id="{{ $ID }}DModal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header text-center">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Are You Sure you want to delete <span id = "delName"></span> category ? it'll also delete all related Sub Categories, Child Categories and Products</h4>
            <br>
            <div>
              <form id = "{{ $ID }}DForm">
                <button type = "button" class="btn btn-danger" id = "yes">Yes</button>
                <button type = "button" class="btn btn-success" data-dismiss="modal">No</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div> --}}
  </div>
</div>

@endsection

@push('footer')
<script src="{{ asset('admin-assets/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
{{-- <script src="{{ asset('admin-assets/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script> --}}
<script src="{{ asset('admin-assets/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
<script src="{{ asset('admin-assets/jszip/dist/jszip.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/vfs_fonts.js') }}"></script>

<script type="text/javascript">  

  Table.init(ID);


</script>
@endpush

laravel/resources/views/admin/view_clients.blade.php
@extends('admin.layouts.master')

@section('title')
{{ is_null($type) ? 'All Clients' : 'New Requests' }}
@endsection
@push('header')
<!-- Datatables -->
<link href="{{ asset('admin-assets/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('admin-assets/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
@php
$ID = '';
@endphp
@endpush

@section('content')

<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>{{ is_null($type) ? 'All Clients' : 'New Requests' }}</h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">            
            <table id="{{ $ID }}Table" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Sr. No.</th>
                  <th>ID</th>
                  <th>NAME</th>
                  <th>EMAIL</th>
                  <th>MOBILE</th>
                  <th>ACTION</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($clients as $k => $c)
                <tr id = "tr-{{ $c->id }}">
                  <td>{{ ++$k }}</td>                  
                  <td>{{ $c->detail->ud_client_id or '-' }}</td>                  
                  <td>{{ $c->name }}</td>          
                  <td>{{ $c->email }}</td>                  
                  <td>{{ $c->detail->ud_mobile or '-' }}</td>                  
                  <td>                    
                    <a href = "{{ route('admin.import', ['id' => $c->id]) }}" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i> Upload </a>|
                    <a href = "{{ route('admin.report', ['id' => $c->id]) }}" class="btn btn-primary btn-xs"><i class="fa fa-list"></i> Weekly Report </a>|
                    
                    @if ($c->approved)
                      <a href = "{{ route('admin.change-status', ['id' => $c->id, 'status' => 0]) }}" class="btn btn-danger btn-xs"><i class="fa fa-times"></i> Disallow Access </a>|
                    @else
                      <a href = "{{ route('admin.change-status', ['id' => $c->id, 'status' => 1]) }}" class="btn btn-success btn-xs"><i class="fa fa-check"></i> Allow Access </a>|
                    @endif
                    
                    <a href = "{{ route('admin.user.edit', ['id' => $c->id]) }}" class="btn btn-success btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                    <form action="{{ route('admin.user.destroy', ['id' => $c->id]) }}" method="post">
                      {{ csrf_field() }}
                      <input type="hidden" name="_method" value="DELETE">
                      <button class="btn btn-danger btn-xs"><i class="fa fa-trash"></i> Delete </button>
                    </form>
                  </td>
                </tr>
                @empty                
                @endforelse
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    {{-- <div class="modal fade" id="{{ $ID }}Modal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="{{ $ID }}ModalLabel">Edit {{ $ID }}</h4>
          </div>
          <div class="modal-body">
            @include('admin.forms.category_form')
          </div>
        </div>
      </div>
    </div> --}}

    {{-- <div class="modal fade" id="{{ $ID }}DModal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header text-center">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Are You Sure you want to delete <span id = "delName"></span> category ? it'll also delete all related Sub Categories, Child Categories and Products</h4>
            <br>
            <div>
              <form id = "{{ $ID }}DForm">
                <button type = "button" class="btn btn-danger" id = "yes">Yes</button>
                <button type = "button" class="btn btn-success" data-dismiss="modal">No</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div> --}}
  </div>
</div>

@endsection

@push('footer')
<script src="{{ asset('admin-assets/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
{{-- <script src="{{ asset('admin-assets/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script> --}}
<script src="{{ asset('admin-assets/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
<script src="{{ asset('admin-assets/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
<script src="{{ asset('admin-assets/jszip/dist/jszip.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ asset('admin-assets/pdfmake/build/vfs_fonts.js') }}"></script>

<script type="text/javascript">  

  Table.init(ID);


</script>
@endpush